run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck      
    - gosimple
    - govet         
    - ineffassign   
    - staticcheck   
    - unused        
    - gofmt         
    - misspell      
    - revive        

linters-settings:
  errcheck:
    check-blank: true
  govet:
    check-shadowing: true

issues:
  exclude-use-default: false
