version: 2

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - staticcheck
    - unused

linters-settings:
  errcheck:
    check-blank: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m